name: platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 1.0.2
homepage: https://github.com/BestBurning/platform_device_id

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: 
      git:
        url: https://github.com/JeeMateTeam/platform_device_id.git
        ref: master
        path: platform_device_id_platform_interface
  platform_device_id_macos:
     git:
        url: https://github.com/JeeMateTeam/platform_device_id.git
        ref: master
        path: platform_device_id_macos
  platform_device_id_linux:
     git:
        url: https://github.com/JeeMateTeam/platform_device_id.git
        ref: master
        path: platform_device_id_linux
  platform_device_id_web:
     git:
        url: https://github.com/JeeMateTeam/platform_device_id.git
        ref: master
        path: platform_device_id_web
  platform_device_id_windows:
     git:
        url: https://github.com/JeeMateTeam/platform_device_id.git
        ref: master
        path: platform_device_id_windows
  
  device_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin
      macos:
        pluginClass: PlatformDeviceIdMacosPlugin
      linux:
        default_package: platform_device_id_linux
      web:
        default_package: platform_device_id_web
      windows:
        default_package: platform_device_id_windows

